---
- name: "Build a container with ansible"
  hosts: localhost
  
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi muhab404/comingsoon-page
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t muhab404/comingsoon-page .

    - name: Push Image to dockerhub
      command: docker push muhab404/comingsoon-page

    - name: run container
      command: docker run -d --name web-container -p 80:80 muhab404/comingsoon-page

